<a href="https://colab.research.google.com/github/l0norm/model/blob/main/deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+2


4

In [ ]:
import torch
import numpy as np

# NUMPY

the default type is float64

In [ ]:
np1 = np.random.rand(2,3,4)
print(np1)


[[[0.02884694 0.79054888 0.48823597 0.21219531]
  [0.10631308 0.27632268 0.87335831 0.8550707 ]
  [0.58304664 0.94284911 0.52921281 0.09578812]]

 [[0.53411119 0.66242921 0.21916948 0.5756071 ]
  [0.48832126 0.69128328 0.1202401  0.75804245]
  [0.85891618 0.22809772 0.24107186 0.6645857 ]]]


array([[[0.02884694, 0.79054888, 0.48823597, 0.21219531],
        [0.10631308, 0.27632268, 0.87335831, 0.8550707 ],
        [0.58304664, 0.94284911, 0.52921281, 0.09578812]],

       [[0.53411119, 0.66242921, 0.21916948, 0.5756071 ],
        [0.48832126, 0.69128328, 0.1202401 , 0.75804245],
        [0.85891618, 0.22809772, 0.24107186, 0.6645857 ]]])

# TENSORS

same as numpy but more powerfull designed for deep learning
default type is float32

In [ ]:
tensor_2d = torch.randn(2,3,4)
print(tensor_2d)
tensor_2d.dtype

# tensor_2d = np1
# tensor_2d.dtype


tensor([[[-0.1544, -0.1971,  0.9030, -1.1673],
         [ 0.1885, -0.3835, -0.0409,  0.7117],
         [-0.0023,  1.2633, -0.4671,  2.2066]],

        [[-1.9265,  0.4477, -0.3338,  0.1116],
         [ 1.0127, -0.0245,  0.6286,  0.1151],
         [-0.6101, -0.1693,  1.1315, -0.5473]]])


torch.float32

In [ ]:
# Reshape and View
my_torch = torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# my_torch = my_torch.reshape(2,5)
# my_torch

my_torch = my_torch.reshape(-1)   #reshaping to 1 rwo without knowing how many collumns
my_torch

# my_torch = my_torch.reshape(2,-1) # reshaping to 2 rows without knowing number of collumns
# my_torch

my_torch = my_torch.reshape(3,-1) # cant reshape 2 rows and the elements are 15
my_torch

my_torch = my_torch.reshape(-1,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

# MATH OPERATIONS

In [ ]:
tensor_a = torch.tensor([1,2,3,4,5])    # each item with the other array item 1 + 6
tensor_b = torch.tensor([6,7,8,9,1])

tensor_a + tensor_b
torch.add(tensor_a, tensor_b)
torch.sub(tensor_b, tensor_a)

torch.mul(tensor_a,tensor_b)
torch.div(tensor_a,tensor_b)

torch.remainder(tensor_a, tensor_b)

torch.pow(tensor_a,tensor_b)

tensor_a.add_(tensor_b)     # adds tensor_b to tensor_a

tensor([     1,    128,   6561, 262144,      5])

# SIMPLE NEURAL NETWORK

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# create a model class that inherits nn.Module
class Model(nn.Module):
  # input layeer(4 features of the flower)-->
  # Hidden layer1 (number of neurons) -->
  # H2(n) -->
  # output(3 classes of iris flowers )
  def __init__(self, input_layer=4, h1=8, h2=9, output_layer=3 ): #4 input for the features ,,, 3 output for the different outputs
    super().__init__()    # initiate nn.Module
    self.fc1 = nn.Linear(input_layer, h1)   #to connect the linear layers with each other
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, output_layer)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.out(x)

    return x


In [ ]:
# start with a random number
torch.manual_seed(41)

#create an object of model
model = Model()