<a href="https://colab.research.google.com/github/l0norm/model/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

-numpy = numeric python
-it has to be the same type

In [ ]:
import numpy as np

np1 = np.array([0,1,2,3,4])
print(np1)
print(np1.shape)

[0 1 2 3 4]


In [ ]:
np2 = np.arange(10)
print(np2)

np3 = np.arange(0,10,2) #from 0 to 10 with step 2
print(np3)

np4 = np.zeros(10)
print(np4)

np5 = np.full((10),6)
print(np5)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6 6 6 6 6 6 6 6 6 6]


## MULTIDIMENSION

In [ ]:
np6 = np.ones((2,10))
print(np6)

np7 = np.full(((3),5),3)
print(np7)

[6 6 6 6 6 6 6 6 6 6]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


## converting list to numpy

In [ ]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[2])

[1 2 3 4 5]
3


## SLICING NUMPY ARRAYS

In [ ]:
npSlice  = np.array([1,2,3,4,5,6,7,8,9])
print(npSlice[1:5]) #slices
print(npSlice[1:6:2]) #1 to 6 in steps of two

print(npSlice[::2])  # in steps of 2
print(npSlice[::3])

print(npSlice[1:])
print(npSlice[-4:-2])  #negative slices

# ============================================slicing multidimensional array
print("=========================================")
npM = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])
print(npM[0:1 , 1:3])      #from 0 to 1 rows , from first to third element


[2 3 4 5]
[2 4 6]
[1 3 5 7 9]
[1 4 7]
[2 3 4 5 6 7 8 9]
[6 7]
[[2 3]]


## Universal functions

In [ ]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])

print(np.sqrt(np1))         #square root of each element
print(np.absolute(np1))     #absoulte values
print(np.exp(np1))          #exponentials

print(np.max(np1))
print(np.min(np1))

print(np.sign(np1))       #returns sign of each element
print(np.sin(np1))        #Trig , sin , cos , log



[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]
[3 2 1 0 1 2 3 4 5 6 7 8 9]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


<ipython-input-20-158a73700903>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))         #square root of each element


## Copy vs view


*  the view changes the original
*   copy doesnt change the original






In [ ]:
np1 = np.array([0,1,2,3,4,5])

np2 = np1.view()

np2[0] = 5
print(f'original np1{np1}')
print(f'original np2{np2}')

np2 = np1.copy()
np2[2] = 1
print(np2)


original np1[5 1 2 3 4 5]
original np2[5 1 2 3 4 5]
[5 1 1 3 4 5]


## SHAPE/RESHAPE , multidimensional

In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)

np2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(np2)
print(np2.shape)

np3 = np1.reshape(3,4)
print(np3)

np1 = np1.reshape(2,3,2)
print(np1)
print(np1.shape)

np2 = np1.reshape(-1)
print(np2)
print(np2.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


## iterations / loops

in a multidimensional array if you print x in a loop it will print the whole array ,, if you want to take each element you need to make another loop

or use nditer ,,iterates for the base level

In [ ]:
np1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np1:
  print(x)      # print each row

# for 2-D
for x in np1:
  for y in x:
     print(y)    # print each element in x
# for 3-D
np1 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np1:
  for y in x:
    for z in y:
      print(z)



# instead of these loops
for x in np.nditer(np1):
  print(x)                  # iterates for each element

[1 2 3 4 5]
[ 6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


## sorting

the original doesnt change ,, only a copy

In [ ]:
np1 = np.array([4,5,6,7,8,34,3,2,1])
print(np.sort(np1))

np1 = np.array([[5,3,2,4,5],[4,2,34,56,6]])
print(np1)
print(np.sort(np1))       # sorts for each row only

[ 1  2  3  4  5  6  7  8 34]
[[ 5  3  2  4  5]
 [ 4  2 34 56  6]]
[[ 2  3  4  5  5]
 [ 2  4  6 34 56]]


# PANDAS

In [14]:
import pandas as pd
import numpy as np
from numpy.random import randn

In [2]:
arr = [5,6,78,23]
var = pd.Series(arr)
var

0     5
1     6
2    78
3    23
dtype: int64

In [3]:
# print a specific value
var[1]

6

In [11]:
# labeling with your own indexes
index = ["A","B","C","D"]
var2 = pd.Series(arr, index)
var2
print(var[2])
print(var2["C"])

78
78


In [13]:
cars = {"Tesla":12, "Mercedes":42, "BMW":3}
print(cars)
var = pd.Series(cars)
print(var)

{'Tesla': 12, 'Mercedes': 42, 'BMW': 3}
Tesla       12
Mercedes    42
BMW          3
dtype: int64


## dataFrame

In [17]:
data = randn(4,3) #rows, columns
rows = ["A", "B", "C", "D"]
cols = ["Monday","Tuesday", "Friday"]

In [19]:
#create data frame
df = pd.DataFrame(data, rows, cols)
df

Monday   Tuesday    Friday
A  0.497840  0.347170 -0.834567
B -0.367336 -0.886286  0.987606
C -0.575478  0.815266 -0.319945
D -1.097139 -2.254088 -2.299867

sometimes you have a large csv file so you cant identify each row and col so ,,,,

In [21]:
#import csv file
df2 = pd.read_csv('sample_data/california_housing_train.csv')
df2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -114.31     34.19                15.0       5612.0          1283.0   
1        -114.47     34.40                19.0       7650.0          1901.0   
2        -114.56     33.69                17.0        720.0           174.0   
3        -114.57     33.64                14.0       1501.0           337.0   
4        -114.57     33.57                20.0       1454.0           326.0   
...          ...       ...                 ...          ...             ...   
16995    -124.26     40.58                52.0       2217.0           394.0   
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
0          1015.0       472.0         1.4936             66900.0  
1          1129.0       463.0         1.8200             80100.0  
2           333.0       117.0         1.6509             85700.0  
3           515.0       226.0         3.1917             73400.0  
4           624.0       262.0         1.9250             65500.0  
...           ...         ...            ...                 ...  
16995       907.0       369.0         2.3571            111400.0  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0  

[17000 rows x 9 columns]

In [37]:
# pulling data out
# df2.loc[0]                  #loc for locate

# #pulling out multiple rows
# df2.loc[[0,2,4]]

# #first 5 rows
# df2.head()

# #certain number of first rows
# df2.head(9)

# df2.tail()
# df2.tail(6)

# df2.info()      # gets basic info about the dataset

# # df2.ndim        # get dimensions

# # df2.dtypes      #col datatypes

df2.describe()
df2['longitude'].describe()

df2['longitude']
df2.longitude       #same thing

df2.iloc[:, 1]

0        34.19
1        34.40
2        33.69
3        33.64
4        33.57
         ...  
16995    40.58
16996    40.69
16997    41.84
16998    41.80
16999    40.54
Name: latitude, Length: 17000, dtype: float64