<a href="https://colab.research.google.com/github/l0norm/model/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy

-numpy = numeric python
-it has to be the same type

In [1]:
import numpy as np

np1 = np.array([0,1,2,3,4])
print(np1)
print(np1.shape)

[0 1 2 3 4]


In [6]:
np2 = np.arange(10)
print(np2)

np3 = np.arange(0,10,2) #from 0 to 10 with step 2
print(np3)

np4 = np.zeros(10)
print(np4)

np5 = np.full((10),6)
print(np5)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[6 6 6 6 6 6 6 6 6 6]


# MULTIDIMENSION

In [7]:
np6 = np.ones((2,10))
print(np6)

np7 = np.full(((3),5),3)
print(np7)

[6 6 6 6 6 6 6 6 6 6]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


# converting list to numpy

In [9]:
my_list = [1,2,3,4,5]
np8 = np.array(my_list)
print(np8)
print(np8[2])

[1 2 3 4 5]
3


# SLICING NUMPY ARRAYS

In [17]:
npSlice  = np.array([1,2,3,4,5,6,7,8,9])
print(npSlice[1:5]) #slices
print(npSlice[1:6:2]) #1 to 6 in steps of two

print(npSlice[::2])  # in steps of 2
print(npSlice[::3])

print(npSlice[1:])
print(npSlice[-4:-2])  #negative slices

# ============================================slicing multidimensional array
print("=========================================")
npM = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]])
print(npM[0:1 , 1:3])      #from 0 to 1 rows , from first to third element


[2 3 4 5]
[2 4 6]
[1 3 5 7 9]
[1 4 7]
[2 3 4 5 6 7 8 9]
[6 7]
[[2 3]]


## Universal functions

In [20]:
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])

print(np.sqrt(np1))         #square root of each element
print(np.absolute(np1))     #absoulte values
print(np.exp(np1))          #exponentials

print(np.max(np1))
print(np.min(np1))

print(np.sign(np1))       #returns sign of each element
print(np.sin(np1))        #Trig , sin , cos , log



[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]
[3 2 1 0 1 2 3 4 5 6 7 8 9]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


<ipython-input-20-158a73700903>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))         #square root of each element


# Copy vs view


*  the view changes the original
*   copy doesnt change the original






In [23]:
np1 = np.array([0,1,2,3,4,5])

np2 = np1.view()

np2[0] = 5
print(f'original np1{np1}')
print(f'original np2{np2}')

np2 = np1.copy()
np2[2] = 1
print(np2)


original np1[5 1 2 3 4 5]
original np2[5 1 2 3 4 5]
[5 1 1 3 4 5]
